# Generated by Django 2.0.3 on 2018-04-02 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dict_keyvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
