# Generated by Django 2.0.3 on 2018-04-02 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_profile_birth_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeyValue',
            new_name='ApiKeys',
        ),
        migrations.DeleteModel(
            name='Dict',
        ),
        migrations.AlterField(
            model_name='apikeys',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile'),
        ),
    ]
