# Generated by Django 2.0.3 on 2018-04-02 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180402_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikeys',
            name='container',
        ),
        migrations.DeleteModel(
            name='ApiKeys',
        ),
    ]
